#!/usr/bin/env bash
# This script displays information about subdomains using dig

get_domain_info() {
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
	subdomains=("www" "lb-01" "web-01" "web-02")
else
	subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
	result=$(dig "$sub.$domain" +short)
	record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
	echo "The subdomain $sub is a $record_type record and points to $result"
done
}

get_domain_info "$1" "$2"
